export { articleMock } from './mocks/data'
export { ArticleList } from './ui/ArticleList/ArticleList'
export { getArticleDetailsData } from './model/selectors/getArticleDetailsData/getArticleDetailsData'
export { ArticleDetails } from './ui/ArticleDetails/ArticleDetails'
export { Article, ArticleView } from './model/types/article'
export type { ArticleDetailsSchema } from './model/types/articleDetailsSchema'
